// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SM.Infrastructure.EF;
using System;

namespace SM.Infrastructure.Migrations
{
    [DbContext(typeof(SMContext))]
    [Migration("20170921002847_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SM.Core.Domain.AdrAdm", b =>
                {
                    b.Property<int>("AdrAdmId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("id_admi");

                    b.Property<string>("inne");

                    b.Property<string>("kierownik");

                    b.Property<string>("kontakt");

                    b.Property<string>("miasto");

                    b.Property<string>("nazwa");

                    b.Property<string>("pna");

                    b.Property<string>("ulica");

                    b.Property<string>("uwagi");

                    b.HasKey("AdrAdmId");

                    b.ToTable("AdrAdms");
                });

            modelBuilder.Entity("SM.Core.Domain.AdrBud", b =>
                {
                    b.Property<int>("AdrBudId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("id_adm");

                    b.Property<string>("id_budy");

                    b.Property<string>("id_osie");

                    b.Property<string>("id_ulic");

                    b.Property<string>("kod_n");

                    b.Property<string>("miasto");

                    b.Property<string>("nr_budowla");

                    b.Property<string>("nr_komp_ol");

                    b.Property<string>("numery");

                    b.Property<string>("osiedle");

                    b.Property<string>("pna");

                    b.Property<string>("ulica");

                    b.HasKey("AdrBudId");

                    b.ToTable("AdrBuds");
                });

            modelBuilder.Entity("SM.Core.Domain.AdrKla", b =>
                {
                    b.Property<int>("AdrKlaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("id_budy");

                    b.Property<string>("id_klat");

                    b.HasKey("AdrKlaId");

                    b.ToTable("AdrKlas");
                });

            modelBuilder.Entity("SM.Core.Domain.AdrLok", b =>
                {
                    b.Property<int>("AdrLokId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("id_budy");

                    b.Property<string>("id_klat");

                    b.Property<string>("id_loka");

                    b.HasKey("AdrLokId");

                    b.ToTable("AdrLoks");
                });

            modelBuilder.Entity("SM.Core.Domain.AdrOsi", b =>
                {
                    b.Property<int>("AdrOsiId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("id_adm");

                    b.Property<string>("id_osie");

                    b.Property<string>("kod_n");

                    b.Property<string>("miasto");

                    b.Property<string>("nazwa");

                    b.Property<string>("nr_dz");

                    b.HasKey("AdrOsiId");

                    b.ToTable("AdrOsis");
                });

            modelBuilder.Entity("SM.Core.Domain.AdrUli", b =>
                {
                    b.Property<int>("AdrUliId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("id_adm");

                    b.Property<string>("id_osie");

                    b.Property<string>("id_ulic");

                    b.Property<string>("miasto");

                    b.Property<string>("nazwa");

                    b.HasKey("AdrUliId");

                    b.ToTable("AdrUlis");
                });

            modelBuilder.Entity("SM.Core.Domain.B07_zglo", b =>
                {
                    b.Property<int>("B07_zgloId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("blok");

                    b.Property<DateTime?>("czas_zglos");

                    b.Property<string>("czyj_koszt");

                    b.Property<DateTime?>("data_insp");

                    b.Property<DateTime?>("data_oper");

                    b.Property<DateTime?>("data_tere");

                    b.Property<DateTime?>("data_wykon");

                    b.Property<DateTime?>("data_zglos");

                    b.Property<DateTime?>("data_zlec");

                    b.Property<DateTime?>("godz_wykon");

                    b.Property<string>("id_admin");

                    b.Property<string>("id_adres");

                    b.Property<string>("id_branz");

                    b.Property<string>("id_oper");

                    b.Property<string>("inspektor");

                    b.Property<string>("lp");

                    b.Property<string>("naleznosc");

                    b.Property<string>("nazwisko");

                    b.Property<string>("nr_prac");

                    b.Property<string>("nr_rw");

                    b.Property<string>("nr_zlec");

                    b.Property<string>("nr_zw");

                    b.Property<string>("numer_zglo");

                    b.Property<string>("numer_zlec");

                    b.Property<string>("opis_wykon");

                    b.Property<string>("rodzaj_ust");

                    b.Property<string>("uwagi1");

                    b.Property<string>("uwagi_wyko");

                    b.Property<string>("uwagi_zlec");

                    b.Property<string>("wykon_zewn");

                    b.Property<string>("wykonawca");

                    b.HasKey("B07_zgloId");

                    b.ToTable("B07_zglos");
                });

            modelBuilder.Entity("SM.Core.Domain.B07_zlec", b =>
                {
                    b.Property<int>("B07_zlecId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("blok");

                    b.Property<DateTime?>("data_oper");

                    b.Property<DateTime?>("data_zlec");

                    b.Property<string>("id_admin");

                    b.Property<string>("id_oper");

                    b.Property<string>("il_godz1");

                    b.Property<string>("il_godz2");

                    b.Property<string>("il_godz3");

                    b.Property<string>("il_godz4");

                    b.Property<string>("il_godz5");

                    b.Property<string>("nr_magaz");

                    b.Property<string>("nr_prac");

                    b.Property<string>("nr_prac1");

                    b.Property<string>("nr_prac2");

                    b.Property<string>("nr_prac3");

                    b.Property<string>("nr_prac4");

                    b.Property<string>("nr_prac5");

                    b.Property<string>("nr_rw");

                    b.Property<string>("nr_zglo1");

                    b.Property<string>("nr_zglo2");

                    b.Property<string>("nr_zglo3");

                    b.Property<string>("nr_zglo4");

                    b.Property<string>("nr_zglo5");

                    b.Property<string>("nr_zlec");

                    b.Property<string>("nr_zw");

                    b.Property<string>("numer_zlec");

                    b.Property<string>("uwagi");

                    b.Property<string>("uwagi1");

                    b.Property<string>("wykonawcy");

                    b.HasKey("B07_zlecId");

                    b.ToTable("B07_zlecs");
                });

            modelBuilder.Entity("SM.Core.Domain.Branza", b =>
                {
                    b.Property<int>("BranzaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nazwa_bran");

                    b.Property<string>("nr_branzy");

                    b.HasKey("BranzaId");

                    b.ToTable("Branzas");
                });

            modelBuilder.Entity("SM.Core.Domain.Osoba", b =>
                {
                    b.Property<int>("OsobaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("imie");

                    b.Property<string>("nazwisko");

                    b.Property<string>("nr_admin");

                    b.Property<string>("nr_osoby");

                    b.Property<string>("typ");

                    b.HasKey("OsobaId");

                    b.ToTable("Osobas");
                });
#pragma warning restore 612, 618
        }
    }
}
